x-db: &db-default



services:
  graphhopper:
    build:
        context: .
        dockerfile: docker/graphhopper.Dockerfile
    container_name: graphhopper
    deploy:
        resources:
            limits:
                memory: 12g
    memswap_limit: 12g
    ports:
      - "8989:8989"
    volumes:
        - ./data/graphhopper/osm:/osm_data
        - ./data/graphhopper/cache:/graph-cache
        - ./data/graphhopper/graphhopper-config.yaml:/config.yaml:ro
        - ./data/graphhopper/models:/custom_models
    environment:
        - OSM_DATA_DIR=/osm_data
        - OSM_DATA_URL=https://download.geofabrik.de/europe/switzerland-latest.osm.pbf
    restart: unless-stopped

  photon:
    build:
      context: .
      dockerfile: docker/photon.Dockerfile
    container_name: photon
    ports:
      - "2322:2322" # Photon runs on port 2322
    volumes:
      - ./data/photon:/photon_data # Persist photon's data
    command: ["-osm-pbf", "/data/switzerland-latest.osm.pbf", "-country-codes", "CH", "-languages", "de,fr,it,en"]
    restart: unless-stopped

  db:
    image: postgis/postgis:17-3.5
    restart: unless-stopped
    command: -c config_file=/etc/postgresql/postgresql.conf
    shm_size: 4gb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    container_name: db
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ${APP_STORAGE_PATH:?err}/db/data:/var/lib/postgresql/data