[project]
name = "job-graph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "django-ninja>=1.4.3",
    "httpx>=0.28.1",
]

[dependency-groups]
dev = [
    "ruff>=0.13.1",
]
