/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Point } from './Point';
import {
    PointFromJSON,
    PointFromJSONTyped,
    PointToJSON,
    PointToJSONTyped,
} from './Point';

/**
 * 
 * @export
 * @interface DistanceCalculation
 */
export interface DistanceCalculation {
    /**
     * 
     * @type {Point}
     * @memberof DistanceCalculation
     */
    abfahrtsort: Point;
    /**
     * 
     * @type {number}
     * @memberof DistanceCalculation
     */
    jobId: number;
    /**
     * 
     * @type {string}
     * @memberof DistanceCalculation
     */
    profile: string;
}

/**
 * Check if a given object implements the DistanceCalculation interface.
 */
export function instanceOfDistanceCalculation(value: object): value is DistanceCalculation {
    if (!('abfahrtsort' in value) || value['abfahrtsort'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    return true;
}

export function DistanceCalculationFromJSON(json: any): DistanceCalculation {
    return DistanceCalculationFromJSONTyped(json, false);
}

export function DistanceCalculationFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistanceCalculation {
    if (json == null) {
        return json;
    }
    return {
        
        'abfahrtsort': PointFromJSON(json['abfahrtsort']),
        'jobId': json['job_id'],
        'profile': json['profile'],
    };
}

export function DistanceCalculationToJSON(json: any): DistanceCalculation {
    return DistanceCalculationToJSONTyped(json, false);
}

export function DistanceCalculationToJSONTyped(value?: DistanceCalculation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abfahrtsort': PointToJSON(value['abfahrtsort']),
        'job_id': value['jobId'],
        'profile': value['profile'],
    };
}

