/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FeatureProperties
 */
export interface FeatureProperties {
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    countrycode?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    county?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    district?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof FeatureProperties
     */
    extent?: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    housenumber?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof FeatureProperties
     */
    osmId?: number;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    osmKey?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    osmType?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    osmValue?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    postcode?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof FeatureProperties
     */
    type?: string;
}

/**
 * Check if a given object implements the FeatureProperties interface.
 */
export function instanceOfFeatureProperties(value: object): value is FeatureProperties {
    return true;
}

export function FeaturePropertiesFromJSON(json: any): FeatureProperties {
    return FeaturePropertiesFromJSONTyped(json, false);
}

export function FeaturePropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'city': json['city'] == null ? undefined : json['city'],
        'country': json['country'] == null ? undefined : json['country'],
        'countrycode': json['countrycode'] == null ? undefined : json['countrycode'],
        'county': json['county'] == null ? undefined : json['county'],
        'district': json['district'] == null ? undefined : json['district'],
        'extent': json['extent'] == null ? undefined : json['extent'],
        'housenumber': json['housenumber'] == null ? undefined : json['housenumber'],
        'name': json['name'] == null ? undefined : json['name'],
        'osmId': json['osm_id'] == null ? undefined : json['osm_id'],
        'osmKey': json['osm_key'] == null ? undefined : json['osm_key'],
        'osmType': json['osm_type'] == null ? undefined : json['osm_type'],
        'osmValue': json['osm_value'] == null ? undefined : json['osm_value'],
        'postcode': json['postcode'] == null ? undefined : json['postcode'],
        'state': json['state'] == null ? undefined : json['state'],
        'street': json['street'] == null ? undefined : json['street'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function FeaturePropertiesToJSON(json: any): FeatureProperties {
    return FeaturePropertiesToJSONTyped(json, false);
}

export function FeaturePropertiesToJSONTyped(value?: FeatureProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'city': value['city'],
        'country': value['country'],
        'countrycode': value['countrycode'],
        'county': value['county'],
        'district': value['district'],
        'extent': value['extent'],
        'housenumber': value['housenumber'],
        'name': value['name'],
        'osm_id': value['osmId'],
        'osm_key': value['osmKey'],
        'osm_type': value['osmType'],
        'osm_value': value['osmValue'],
        'postcode': value['postcode'],
        'state': value['state'],
        'street': value['street'],
        'type': value['type'],
    };
}

