/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Geometry
 */
export interface Geometry {
    /**
     * 
     * @type {Array<any>}
     * @memberof Geometry
     */
    coordinates: Array<any>;
    /**
     * 
     * @type {string}
     * @memberof Geometry
     */
    type: string;
}

/**
 * Check if a given object implements the Geometry interface.
 */
export function instanceOfGeometry(value: object): value is Geometry {
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function GeometryFromJSON(json: any): Geometry {
    return GeometryFromJSONTyped(json, false);
}

export function GeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Geometry {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinates': json['coordinates'],
        'type': json['type'],
    };
}

export function GeometryToJSON(json: any): Geometry {
    return GeometryToJSONTyped(json, false);
}

export function GeometryToJSONTyped(value?: Geometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinates': value['coordinates'],
        'type': value['type'],
    };
}

