/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IsoPolygon } from './IsoPolygon';
import {
    IsoPolygonFromJSON,
    IsoPolygonFromJSONTyped,
    IsoPolygonToJSON,
    IsoPolygonToJSONTyped,
} from './IsoPolygon';

/**
 * 
 * @export
 * @interface IsochroneOut
 */
export interface IsochroneOut {
    /**
     * 
     * @type {Array<IsoPolygon>}
     * @memberof IsochroneOut
     */
    polygons: Array<IsoPolygon>;
}

/**
 * Check if a given object implements the IsochroneOut interface.
 */
export function instanceOfIsochroneOut(value: object): value is IsochroneOut {
    if (!('polygons' in value) || value['polygons'] === undefined) return false;
    return true;
}

export function IsochroneOutFromJSON(json: any): IsochroneOut {
    return IsochroneOutFromJSONTyped(json, false);
}

export function IsochroneOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsochroneOut {
    if (json == null) {
        return json;
    }
    return {
        
        'polygons': ((json['polygons'] as Array<any>).map(IsoPolygonFromJSON)),
    };
}

export function IsochroneOutToJSON(json: any): IsochroneOut {
    return IsochroneOutToJSONTyped(json, false);
}

export function IsochroneOutToJSONTyped(value?: IsochroneOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'polygons': ((value['polygons'] as Array<any>).map(IsoPolygonToJSON)),
    };
}

