/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsoPolygon
 */
export interface IsoPolygon {
    /**
     * 
     * @type {Array<Array<Array<any>>>}
     * @memberof IsoPolygon
     */
    rings: Array<Array<Array<any>>>;
}

/**
 * Check if a given object implements the IsoPolygon interface.
 */
export function instanceOfIsoPolygon(value: object): value is IsoPolygon {
    if (!('rings' in value) || value['rings'] === undefined) return false;
    return true;
}

export function IsoPolygonFromJSON(json: any): IsoPolygon {
    return IsoPolygonFromJSONTyped(json, false);
}

export function IsoPolygonFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsoPolygon {
    if (json == null) {
        return json;
    }
    return {
        
        'rings': json['rings'],
    };
}

export function IsoPolygonToJSON(json: any): IsoPolygon {
    return IsoPolygonToJSONTyped(json, false);
}

export function IsoPolygonToJSONTyped(value?: IsoPolygon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'rings': value['rings'],
    };
}

