/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobOpeningOut
 */
export interface JobOpeningOut {
    /**
     * 
     * @type {string}
     * @memberof JobOpeningOut
     */
    companyName: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof JobOpeningOut
     */
    location?: Array<any> | null;
    /**
     * 
     * @type {string}
     * @memberof JobOpeningOut
     */
    title: string;
}

/**
 * Check if a given object implements the JobOpeningOut interface.
 */
export function instanceOfJobOpeningOut(value: object): value is JobOpeningOut {
    if (!('companyName' in value) || value['companyName'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function JobOpeningOutFromJSON(json: any): JobOpeningOut {
    return JobOpeningOutFromJSONTyped(json, false);
}

export function JobOpeningOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobOpeningOut {
    if (json == null) {
        return json;
    }
    return {
        
        'companyName': json['company_name'],
        'location': json['location'] == null ? undefined : json['location'],
        'title': json['title'],
    };
}

export function JobOpeningOutToJSON(json: any): JobOpeningOut {
    return JobOpeningOutToJSONTyped(json, false);
}

export function JobOpeningOutToJSONTyped(value?: JobOpeningOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company_name': value['companyName'],
        'location': value['location'],
        'title': value['title'],
    };
}

