/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PolygonGeometry } from './PolygonGeometry';
import {
    PolygonGeometryFromJSON,
    PolygonGeometryFromJSONTyped,
    PolygonGeometryToJSON,
    PolygonGeometryToJSONTyped,
} from './PolygonGeometry';

/**
 * 
 * @export
 * @interface Polygon
 */
export interface Polygon {
    /**
     * 
     * @type {PolygonGeometry}
     * @memberof Polygon
     */
    geometry: PolygonGeometry;
}

/**
 * Check if a given object implements the Polygon interface.
 */
export function instanceOfPolygon(value: object): value is Polygon {
    if (!('geometry' in value) || value['geometry'] === undefined) return false;
    return true;
}

export function PolygonFromJSON(json: any): Polygon {
    return PolygonFromJSONTyped(json, false);
}

export function PolygonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Polygon {
    if (json == null) {
        return json;
    }
    return {
        
        'geometry': PolygonGeometryFromJSON(json['geometry']),
    };
}

export function PolygonToJSON(json: any): Polygon {
    return PolygonToJSONTyped(json, false);
}

export function PolygonToJSONTyped(value?: Polygon | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'geometry': PolygonGeometryToJSON(value['geometry']),
    };
}

