/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolygonGeometry
 */
export interface PolygonGeometry {
    /**
     * 
     * @type {Array<Array<any>>}
     * @memberof PolygonGeometry
     */
    coordinates: Array<Array<any>>;
}

/**
 * Check if a given object implements the PolygonGeometry interface.
 */
export function instanceOfPolygonGeometry(value: object): value is PolygonGeometry {
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function PolygonGeometryFromJSON(json: any): PolygonGeometry {
    return PolygonGeometryFromJSONTyped(json, false);
}

export function PolygonGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolygonGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'coordinates': json['coordinates'],
    };
}

export function PolygonGeometryToJSON(json: any): PolygonGeometry {
    return PolygonGeometryToJSONTyped(json, false);
}

export function PolygonGeometryToJSONTyped(value?: PolygonGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'coordinates': value['coordinates'],
    };
}

