/* tslint:disable */
/* eslint-disable */
/**
 * NinjaAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SearchSchema
 */
export interface SearchSchema {
    /**
     * 
     * @type {string}
     * @memberof SearchSchema
     */
    name: string | null;
}

/**
 * Check if a given object implements the SearchSchema interface.
 */
export function instanceOfSearchSchema(value: object): value is SearchSchema {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SearchSchemaFromJSON(json: any): SearchSchema {
    return SearchSchemaFromJSONTyped(json, false);
}

export function SearchSchemaFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchSchema {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SearchSchemaToJSON(json: any): SearchSchema {
    return SearchSchemaToJSONTyped(json, false);
}

export function SearchSchemaToJSONTyped(value?: SearchSchema | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

