# Generated by Django 5.2.6 on 2025-09-29 09:15

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('workplace_zip', models.CharField(blank=True, max_length=20)),
                ('workplace_city', models.CharField(blank=True, max_length=255)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=500), default=list, size=None)),
                ('first_seen_date', models.DateTimeField(auto_now_add=True)),
                ('last_seen_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('company_name', 'title', 'workplace_zip')},
            },
        ),
    ]
