# Generated by Django 5.2.6 on 2025-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='raw_data',
            field=models.JSONField(default=list, help_text='A list of the raw JSON objects from each source, in the same order as the URLs.'),
        ),
    ]
