# Generated by Django 5.2.6 on 2025-09-29 11:55

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jobopening_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='home_office',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Cast('raw_data__homeOffice', models.BooleanField()), output_field=models.BooleanField()),
        ),
    ]
