# Generated by Django 5.2.6 on 2025-09-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_jobopening_home_office'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='first_seen_date',
            new_name='first_seen_at',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='last_seen_date',
            new_name='last_seen_at',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='first_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
