# Generated by Django 5.2.6 on 2025-09-29 13:33

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_first_seen_date_jobopening_first_seen_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopening',
            name='platform_id',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.comparison.Cast('raw_data__id', models.IntegerField()), output_field=models.IntegerField()),
        ),
    ]
