# Generated by Django 5.2.6 on 2025-09-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_jobopening_platform_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='raw_data',
            field=models.JSONField(default=dict, help_text='A list of the raw JSON objects from each source, in the same order as the URLs.'),
        ),
    ]
