# Generated by Django 5.2.6 on 2025-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_jobopening_raw_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='urls',
        ),
        migrations.AddField(
            model_name='jobopening',
            name='url_application',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='url_description',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
