# Generated by Django 5.2.6 on 2025-09-29 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_jobopening_urls_jobopening_url_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopening',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
