# Generated by Django 5.2.6 on 2025-09-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_jobopening_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopening',
            old_name='workplace_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='jobopening',
            old_name='workplace_zip',
            new_name='zip',
        ),
        migrations.AlterUniqueTogether(
            name='jobopening',
            unique_together={('company_name', 'title', 'zip')},
        ),
        migrations.AddField(
            model_name='jobopening',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='jobopening',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
